### ISSUE TITLE
Need to delete dashboard twice

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#10]
If I wnt to delete a dashboard, it doesn't delete the first time. The first time, all the graphs disappear, but the dashboard stays. so I need to re-delete it.

**Comment by nextchamp-saqib** [comment]
I couldn't replicate it. Check if the issue still exists. If it does, please re-open the issue.

![CleanShot 2022-09-12 at 17 25 54](https://user-images.githubusercontent.com/25369014/189647265-7a14ba2d-b121-4329-b77c-164b09f89eb8.gif)

**Comment by michellealva** [comment]
@nextchamp-saqib yes, this is working now.
