### ISSUE TITLE
Column name changes after update

### ISSUE THREAD

**Issue by pateljannat** [frappe/insights#101]
<img width="1440" alt="Screenshot 2023-03-15 at 5 25 04 PM" src="https://user-images.githubusercontent.com/31363128/225302044-5dd5d31f-6619-4f98-b098-1578d49603a8.png">

On update of column, the column name changes to the value of label.

**Comment by nextchamp-saqib** [comment]
This should be fixed with the new query builder (https://github.com/frappe/insights/pull/185)
