### ISSUE TITLE
Pricing ?

### ISSUE THREAD

**Issue by denzizzy966** [frappe/insights#106]
this pricing is for many domain or just once ?

**Comment by nextchamp-saqib** [comment]
Hey, sorry I didn't get your question, which pricing are you talking about?

**Comment by denzizzy966** [comment]
https://frappecloud.com/marketplace/apps/insights

this $10/month

**Comment by nextchamp-saqib** [comment]
The 10$ pricing is for those who want to host on Frappe Cloud (FC) preferably those who already have an erpnext instance on FC
You can still host your free version of Insights by forking and adding a custom app source on your custom bench on FC

Does this answer your query?

**Comment by denzizzy966** [comment]
thanks for your information sir saqib
