### ISSUE TITLE
Site DB and Query DB not working

### ISSUE THREAD

**Issue by bhickta** [frappe/insights#117]
Installed insights on existing website with follow specs:
frappe                 14.34.0    version-14
erpnext                14.23.0    version-14
payments               0.0.1      develop
ecommerce_integrations 1.15.4     main
india_compliance       14.6.1     version-14
helpdesk               0.8.1      main
hrms                   15.0.0-dev develop
But insights on site db not working and showing nothing:

![image](https://user-images.githubusercontent.com/61617746/234761641-7eae044e-d986-45c4-96a0-521d71609dd7.png)

In query builder, no table is shown for site-db
![image](https://user-images.githubusercontent.com/61617746/234761883-877b7091-101f-4a13-9104-0bd6f81153bb.png)

Only demo data is showing tables

**Comment by nextchamp-saqib** [comment]
Did you sync the tables? ref. [docs](https://docs.frappeinsights.com/data-source/overview.html#syncing-schema)

**Comment by bhickta** [comment]
Yes i did sync the tables
