### ISSUE TITLE
duplicate column name 'name' error

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/insights#118]
![CleanShot 2023-04-27 at 11 37 25](https://user-images.githubusercontent.com/25369014/234774157-c14632d9-4533-488b-9a35-c10f945bfcba.png)

**Comment by azurre931** [comment]
Can this be tagged a "Priority", we can't use Insights currently because of this error. Thank you :)

**Comment by nextchamp-saqib** [comment]
It only occurs if there's no columns selected (in the middle section)
An easy workaround is to select at least one column and then add a join

But I too face it often. will prioritise it
