### ISSUE TITLE
Frappe Insights

### ISSUE THREAD

**Issue by WANASWA** [frappe/insights#119]
Hi i'm new to insights and would like to have the analytical dashboard for healthcare facility that i manage. Can I get some help to do this please

**Comment by nextchamp-saqib** [comment]
Hey, Thanks for reaching out! While I'm not a healthcare expert, I can help you with installing frappe insights and fixing any bugs you encounter while using insights

To get started, you need to have your data ready and the metrics decided already.
You can check out the documentation at docs.frappeinsights.com for any help.

If you're an ERPNext user on frappe cloud, you can quickly test insights by visiting https://frappecloud.com/marketplace/apps/insights

Feel free to ask for help with installation or any other issues you come across

**Comment by WANASWA** [comment]
hI

Is it possible to get support for integration to data source in  
progress database and or SQL?
WANASWA EDWARD
GENERAL MANAGER
P.O. BOX 75162 KAMPALA UGANDA.
TEL: +256 392 177 822
MOB & WHATSAPP:  +256 751 963 275
EMAIL: ***@***.***
WEBSITE: WWW.ENTERPRISESYSTEMS.CO.UG[1]


Links:
------
[1] http://www.enterprisesystems.co.ug/

**Comment by ESLTDUG** [comment]
Hi Saqib can you help to connect to SQL Data Source. I have not used Insight for a month now since install because my data is in SQL
