### ISSUE TITLE
Cannot compile - widget_data.py

### ISSUE THREAD

**Issue by redolencetech** [frappe/insights#122]
I'm getting an error of inconsistent use of tabs and spaces in indentation

<img width="939" alt="image" src="https://user-images.githubusercontent.com/6630615/236390796-f0e0f7fe-0bfe-43cd-b443-27f63bab2ecb.png">

**Comment by nextchamp-saqib** [comment]
This doesn't seems to be related to insights. There must be a different app called "dashboard" which is causing the error

**Comment by redolencetech** [comment]
Yep you were right, apologies for the mixup!
