### ISSUE TITLE
copy sql adds HTML break tags in copied query

### ISSUE THREAD

**Issue by ankush** [frappe/insights#123]
```SELECT date_format(t0.creation, '%%Y-%%m-%%d') AS `Date`,<br>&ensp;&ensp;&ensp;&ensp; avg(t0.seen) * 100 AS `error log seen`<br>  FROM `tabError Log` AS t0<br> GROUP BY date_format(t0.creation, '%%Y-%%m-%%d')<br> ORDER BY date_format(t0.creation, '%%Y-%%m-%%d') ASC<br> LIMIT 500```

**Comment by nextchamp-saqib** [comment]
Fixed (15a7586)
