### ISSUE TITLE
Number display format

### ISSUE THREAD

**Issue by Suprazz** [frappe/insights#128]
When selecting Widget Type Number, the default way of displaying big numbers is pretty unusual like 1.24L of the "Shorten Numbers" is enabled.

But when disabled it's even weirder... I get 1,23,877.79... not sure why a comma between 1 and the 2....

![image](https://github.com/frappe/insights/assets/3640711/a9899729-68a9-4320-ae2b-ba54748a4dd9)

**Comment by nextchamp-saqib** [comment]
This was done as per expected number format for us internally 

Let me know which format do you expect to see in the shorten version as well as the long version

I'll make it configurable

**Comment by nextchamp-saqib** [comment]
It is now configurable. You can set the **Language** in the **System Settings** which will be used to format the numbers in Insights
