### ISSUE TITLE
Not able to click or open any of them 

### ISSUE THREAD

**Issue by Gurukrupa-Export** [frappe/insights#138]
![image](https://github.com/frappe/insights/assets/129185339/e70a2895-970c-4cd5-8694-8f67768ca56f)

**Comment by nextchamp-saqib** [comment]
is there any error in the javascript console?

**Comment by azharrahman021** [comment]
![Screenshot 2023-07-18 052212](https://github.com/frappe/insights/assets/42474457/438c37e5-d7f8-4155-809f-eec3832de88a)
Here is what Im getting on the console @nextchamp-saqib

**Comment by Suprazz** [comment]
I have the same error. Tried with version 1.0.0.
This is the error I get when I try to create a query. Database connection work well and I can browse the tables.

frappe-ui-ae56a352.js:1 Error: insights.api.create_query LinkValidationError

    at frappe-ui-ae56a352.js:238:5045

    at [Generator.next](http://generator.next/) (<anonymous>)

    at o (frappe-ui-ae56a352.js:1:668)

**Comment by nextchamp-saqib** [comment]
fixed: 4e6f8e9770672b364f58a8a08ab56d9cc3fd6d95
