### ISSUE TITLE
Allow import of excel/CSV to create charts

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#14]
right now i can only create reports through queries with some data source through a database.

**Comment by michellealva** [comment]
@nextchamp-saqib also and additional option to directly add data into insights without CSV/Excel too (like how it works in spreadsheets now, if you could give a tabular view just like sheets and ask the user to enter directly in insights instead of import)

**Comment by ankush** [comment]
generic extension of this is: to define data source interface that others can plug into. 

e.g. virtual doctypes  (badly done, but you get the idea)

**Comment by nextchamp-saqib** [comment]
Added CSV import

<img width="1440" alt="CleanShot 2022-11-03 at 13 26 09@2x" src="https://user-images.githubusercontent.com/25369014/200110773-438b10e1-8c1b-4251-bcbb-9cd0e371dccb.png">

I will later attempt to make CSV data work without importing
