### ISSUE TITLE
Want some new charts types & Mobile UI Issue

### ISSUE THREAD

**Issue by precihole** [frappe/insights#149]
Hello Sir,

We are really happy to use insights. However, we need other chart kinds, such as scatter plots,funnel, Pareto charts, and histograms.
Additionally, the mobile view is still somewhat confusing.
Destop View
<img width="923" alt="image" src="https://github.com/frappe/insights/assets/111174201/49262c26-f687-4e77-848d-7c4ef13043f3">
<img width="916" alt="image" src="https://github.com/frappe/insights/assets/111174201/ac86a514-6061-448b-b169-0fdf709910fb">

Mobile View
<img width="118" alt="image" src="https://github.com/frappe/insights/assets/111174201/b56ec5aa-3cec-46fa-8ae2-73a845e1c715">
<img width="115" alt="image" src="https://github.com/frappe/insights/assets/111174201/9c07475a-5c15-4432-824b-924696421cc1">

So I guess in mobile view  only the left side chart are coming.

Thanks & Regards,
Midhat Ayesha Shaikh

**Comment by nextchamp-saqib** [comment]
The responsiveness issue has been fixed. Also, there are two new `scatter` and `funnel` charts added. (on latest `develop` branch)
