### ISSUE TITLE
Dashboard filters not working

### ISSUE THREAD

**Issue by ishanloya** [frappe/insights#150]
I'm running the latest version of insights locally. I don't think the dashboard filters are working. I'm getting the same results in charts even with filters. I have linked the chart to the dashboard filter.

**Comment by nextchamp-saqib** [comment]
It's working for me. Try re-linking your filters maybe?

![CleanShot 2023-08-09 at 15 44 33](https://github.com/frappe/insights/assets/25369014/7e7cda09-e9ed-41b1-9262-7e31841e7083)

**Comment by JeansReal** [comment]
Running in v1.1.1 and filter are not working

Installed the site in Frappe v14, can the issue be related?

**Comment by nextchamp-saqib** [comment]
This should be working now (on the latest `develop` branch). There was an issue while refreshing the chart when filters were changed.
