### ISSUE TITLE
We are not able to generate new queries 

### ISSUE THREAD

**Issue by precihole** [frappe/insights#151]
We are unable to construct new queries, and nothing works when we click on all of the query types (Visual, Classic, and SQL).
![Screenshot from 2023-08-09 12-00-22](https://github.com/frappe/insights/assets/111174201/c773c7b0-640d-4554-ae07-1a7d70765c5b)

**Comment by nextchamp-saqib** [comment]
Merged the fix into the main branch, update your branch to fix the issue.
