### ISSUE TITLE
Bench update results in error

### ISSUE THREAD

**Issue by mrPauwHaan** [frappe/insights#162]
When running `bench update` I am getting the error `You have local changes in app "insights" that are not committed.`. I have to use the `--reset` flag to update all of my modules. Also, the latest version it is installing is insights 1.0.1, while it should be updating to the latest version available.

**Comment by nextchamp-saqib** [comment]
This isn't related to `insights`
As a workaround, you can manually pull latest changes using `git pull` and then run `bench --site <your-site> migrate`
