### ISSUE TITLE
Date Formate is not Working

### ISSUE THREAD

**Issue by precihole** [frappe/insights#163]
Hello, @nextchamp-saqib 

After applying date formate when click on update button then it is vanished as shown in image 2.
It is Insights issue or frappe issue?
Frappe Insights: v1.1.2 (HEAD)
![image](https://github.com/frappe/insights/assets/111174201/8d9617e1-face-4c25-9390-8338ad904ca0)

![image](https://github.com/frappe/insights/assets/111174201/a747570f-9317-4ff6-832d-2ed3580927e1)

**Comment by nextchamp-saqib** [comment]
update to v1.1.3 it should be fixed
