### ISSUE TITLE
Visual Builder UX

### ISSUE THREAD

**Issue by ankush** [frappe/insights#168]

**Comment by ankush** [comment]
Make "next step" obvious? Grayed out right now

![image](https://github.com/frappe/insights/assets/9079960/d1dd7b9b-431d-440c-b53c-7e0e8c309927)

**Comment by ankush** [comment]
Assume equals is the default filter - most common use case

![image](https://github.com/frappe/insights/assets/9079960/ad1bfe7d-edb4-482d-ba92-0b8e18467f59)

**Comment by ankush** [comment]
- [ ] Ctrl+E doesn't work on Windows/Linux
- [ ] Audit all keyboard shortcut to support ctrl instead of cmd on linux

**Comment by ankush** [comment]
Calculated column should be selected by default? 

![image](https://github.com/frappe/insights/assets/9079960/6add5eb6-4477-4911-abe7-2aaf1d0a5e1c)

**Comment by ankush** [comment]
Select `sum of` by default as aggregation

![image](https://github.com/frappe/insights/assets/9079960/e41881a1-4594-486a-ac1c-ebf6497bf681)

**Comment by nextchamp-saqib** [comment]
Not needed after https://github.com/frappe/insights/pull/185
