### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by webbosolutions** [frappe/insights#175]
ImportError: Module import failed for Insights Dashboard, the DocType you're trying to open might be deleted.<br> Error: No module named 'posthog'

**Comment by nextchamp-saqib** [comment]
Make sure you are on frappe framework v14
If you are on v14 then run `bench setup requirements --python`

**Comment by nextchamp-saqib** [comment]
reopen if the problem persists after trying the above

**Comment by webbosolutions** [comment]
Sorry but same problem i cannot also update frappe
