### ISSUE TITLE
Number Cards - Labels hidden

### ISSUE THREAD

**Issue by rtdany10** [frappe/insights#177]
`.overflow-hidden` causes labels to be hidden on my screen

https://github.com/frappe/insights/assets/52111700/f98ff329-982e-4b3f-bf75-3d2614d86500

Resizing the number card did solve the issue, but still, we shouldn't be hiding the labels imo

**Comment by rtdany10** [comment]
I was tbh scratching my head cause I remember setting up the label but it was missing when the card was added to the dashboard. Then looking at the CSS, I understood it was the overflow attribute hiding it.

Maybe let it overflow? People can resize it always.

**Comment by nextchamp-saqib** [comment]
Done (ref. 134956d91af036cbae33b9b337a2e4ccee9ed89e)
