### ISSUE TITLE
Unable to share dashboards with users

### ISSUE THREAD

**Issue by ekomim** [frappe/insights#178]
I have created dashboards with the administrator account but I am unable to share them with users who do not have the Frappe role "System Manager". The user I am trying to share the dashboard with has the Frappe roles "Insights User" and "Insight Admin" and also has access the Doctypes used to create the charts. I have also added said user to an Insights Team and have shared the dashboard with that team.

![image](https://github.com/frappe/insights/assets/148065696/524e297e-f92a-48ba-8b3f-30ea56c229ab)

**Comment by nextchamp-saqib** [comment]
I have pushed a fix. Update and check now
