### ISSUE TITLE
Visual dashboard not updated dynamically  + Filter 

### ISSUE THREAD

**Issue by NehaSan16** [frappe/insights#183]
#! The visual dashboard does not get updated dynamically whenever the data or the analysis table undergoes changes. 
Have sent you screenshots separately on telegram. 

#2 Unable to see columns when creating a new filter in a dashboard 
![Uploading Screenshot 2023-11-09 at 12.00.40 PM.png…]()
![Uploading Screenshot 2023-11-09 at 12.01.25 PM.png…]()

**Comment by nextchamp-saqib** [comment]
Should be fixed with the v2 release.
