### ISSUE TITLE
Error while Installing Insight App over the site

### ISSUE THREAD

**Issue by jaydeep-sigzen** [frappe/insights#187]
Hello I am getting below error during the install insight app in site.

  **File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'table)' at line 2")**

Frappe - 14
ErpNext- 14
India Compliance - 14
Insight - develop

**Comment by nextchamp-saqib** [comment]
This has been fixed. Please update to latest `develop` and check
