### ISSUE TITLE
Prompt overlaps with expression

### ISSUE THREAD

**Issue by NehaSan16** [frappe/insights#188]
![telegram-cloud-photo-size-5-6287108656034068986-y](https://github.com/frappe/insights/assets/139349833/cc8d923b-38de-44a3-8142-6ff91e05a082)

As attached, the prompt seems to be overlapping with the text edit box. We should fix this.

**Comment by nextchamp-saqib** [comment]
Will be fixed with https://github.com/frappe/insights/pull/199
