### ISSUE TITLE
Unable to Update Past v1.1.3

### ISSUE THREAD

**Issue by aheart** [frappe/insights#190]
I've ran bench update multiple times, but I'm always stuck on v1.1.3
Could this be caused by the fact that the develop branch has v1.1.3 here?
https://github.com/frappe/insights/blob/develop/insights/__init__.py#L5

Or maybe it's caused by the fact that I'm on **develop** and instead should switch to **main**?

![image](https://github.com/frappe/insights/assets/9392791/99fb1714-6ea1-4bfb-a031-8e4ca92b10f4)

**Comment by nextchamp-saqib** [comment]
Ignore the version if you are on develop branch. There's an issue updating the version on the develop branch I haven't figured it out yet.
