### ISSUE TITLE
Error Message Visibility Duration in ERPNext Insight

### ISSUE THREAD

**Issue by shubhampreciholesports** [frappe/insights#193]
When I execute the SQL script in ERPNext Insight and encounter a SQL error, the error message is displayed for only 3 seconds before disappearing. I would like the error message to remain visible until I manually close it by clicking the cross button.
![Uploading ss.png…]()

**Comment by shubhampreciholesports** [comment]
![Uploading ss.png…]()

**Comment by nextchamp-saqib** [comment]
I'll be working on improving error handling later next month. 
Until then please use the browser console (ctrl+shift+j) to check the error message

**Comment by shubhampreciholesports** [comment]
ok thankyou
