### ISSUE TITLE
Pivot option is not working

### ISSUE THREAD

**Issue by kittiu** [frappe/insights#225]
### I did a very basic query ”Purchase by Partner by Quarter”

![image](https://github.com/frappe/insights/assets/1973598/d09c5a73-9aee-401c-8752-9489e27bd6fb)

### If I add the PIVOT

![image](https://github.com/frappe/insights/assets/1973598/642a0f0f-cfb6-4235-92d6-919123cae433)

### It will not give any result,

![image](https://github.com/frappe/insights/assets/1973598/7ccdebd6-0109-4b49-87ff-1b6b8a20e4ab)

**Comment by nextchamp-saqib** [comment]
Is there any error in the browser console?

**Comment by kittiu** [comment]
Nothing, here is the VDO

![bug](https://github.com/frappe/insights/assets/1973598/76f5e7f0-dd20-47af-8c4e-ffb224035e68)

**Comment by nextchamp-saqib** [comment]
Got it. It seems like a bug. I'll update you once it's fixed
