### ISSUE TITLE
Shared a dashboard as <iframe> is not working on other site.

### ISSUE THREAD

**Issue by kittiu** [frappe/insights#226]
I try this feature <iframe>

![image](https://github.com/frappe/insights/assets/1973598/2b971884-60a9-49c8-9169-b8df327d0ad8)

And it works if I create a custom html block on the same url.

But I want to share this <iframe> to other sites, it won't work. 

Some research tell me this is not possible. https://discuss.frappe.io/t/calling-erpnext-in-iframe-from-wordpress/18529/8

Are the work around or future enhancement? As I think this feature will be very useful if it can be used else where too. Thanks

**Comment by nextchamp-saqib** [comment]
Copy the Link and then open it in an incognito tab. Let me know if you can see the chart. If yes, then the iframe should work anywhere.

Also check https://docs.frappeinsights.com/miscellaneous/faq.html#q-how-do-i-view-charts-dashboard-on-my-frappe-erpnext-site

**Comment by kittiu** [comment]
Yes, I did that. And it works on Incognito. Also work on the same site as insights installation (same URL).

But it is not working on other frappe site which is due to NGINX restriction. https://discuss.frappe.io/t/calling-erpnext-in-iframe-from-wordpress/18529/11

Anyway, I think it is not related to frappe. Thanks!
