### ISSUE TITLE
frontend/src/components/AlertDialog.vue formatting issue

### ISSUE THREAD

**Issue by rehanansari26** [frappe/insights#227]
templates are not highlighting so it not readable as other components are as shown in image?

AlertDialog.vue Issue
![image](https://github.com/frappe/insights/assets/110723484/8d7a054a-c0a9-4ad0-8d82-b2a839a98b66)

AppShell.vue
![image](https://github.com/frappe/insights/assets/110723484/90394445-3a29-46d7-9202-bf0b9abcd6ac)

**Comment by rehanansari26** [comment]
@shariquerik

**Comment by nextchamp-saqib** [comment]
It seems that this functions correctly in VSCode, so there doesn't appear to be any issue
