### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/insights/setup.py'

### ISSUE THREAD

**Issue by aryanrajput** [frappe/insights#229]
**Frappe Insights installation error:**
FileNotFoundError: [Errno 2] No such file or directory: '/home/frappe/frappe-bench/apps/insights/setup.py'

bench version - 14

![image](https://github.com/frappe/insights/assets/26869121/b3caaac7-4f2b-4e9a-b82c-41d477180c28)

**Comment by aryanrajput** [comment]
I have installed on local via same way then its working but on my server its is not working.

**Comment by nextchamp-saqib** [comment]
can you confirm if the bench --version on both machine is the same?

**Comment by aryanrajput** [comment]
local machine: 
![image](https://github.com/frappe/insights/assets/26869121/828f5d78-44c5-4f36-aac7-1d96284444c6)

server machine:
![image](https://github.com/frappe/insights/assets/26869121/85914d5d-4e66-4296-8cd6-1e86fefe7cf4)

**Comment by nextchamp-saqib** [comment]
The bench version on the server machine is very old. Update your bench version to `5.20` and it should fix the issue
