### ISSUE TITLE
Question: insights + v13?

### ISSUE THREAD

**Issue by reddaoist** [frappe/insights#230]
I am sure that this is not the right channel to ask questions about the insights app. Apologies in advance.

I was intending to ask my questions on the telegram group, but the when accessing the TG link on the repo, it does not load and it says `This site can't be reached.`
...

Is it possible to make the insights app work with v13 frappe?

**Comment by nextchamp-saqib** [comment]
Insights should be used with frappe v14+ only as frappe framework v13 is no longer [actively supported](https://discuss.frappe.io/t/reminder-v13-is-end-of-life/110557). You can maintain a separate bench for Insights with frappe v14.

Also, Telegram link is working for me. Maybe some temporary issue (?)
