### ISSUE TITLE
Add Filter Row for pitvot table

### ISSUE THREAD

**Issue by NehaSan16** [frappe/insights#235]
Earlier pivot table also had filter row and total row. Can we please bring it back. it was a very helpful feature. 

<img width="1051" alt="Screenshot 2024-03-18 at 10 46 23 PM" src="https://github.com/frappe/insights/assets/139349833/2847f8ac-c36d-4505-ad9a-c26a096f21a8">

**Comment by nextchamp-saqib** [comment]
added: https://github.com/frappe/insights/commit/edf9101f01e3afb7d579d5056d7955aaaa31630c
