### ISSUE TITLE
unable to select a query

### ISSUE THREAD

**Issue by phot0n** [frappe/insights#246]
https://github.com/frappe/insights/assets/32034600/227776a3-a63a-494f-8352-66f3e9f4e94e

While trying to click on checkbox, it takes me to the specific query page.
Also, when i select all and try to uncheck a query, the same thing happens.

**Comment by nextchamp-saqib** [comment]
The video isn't working for me. Maybe try uploading again?

**Comment by nextchamp-saqib** [comment]
Reopen the issue once you have updated the video link
