### ISSUE TITLE
Frappe Bench Installtion with Insights 

### ISSUE THREAD

**Issue by sameerhassan888** [frappe/insights#250]
Bench Installation is not working as per the document.

https://frappeframework.com/docs/user/en/installation 

its not working i think need to update. issues some packages not exists, version of node is old to install insights app, no virtual env documentation

When I install Frappe insights with sitename its not working show 404 error 'to fixed i use  -  bench use sitename'

**Comment by nextchamp-saqib** [comment]
Are you facing issues installing frappe bench or frappe insights? Please elaborate more for me to check the issue like any errors/traceback that you had faced

Reopen the issue with more context
