### ISSUE TITLE
Deployment error on Frappe v14 - insights-frontend version check

### ISSUE THREAD

**Issue by eleben** [frappe/insights#255]
Issue with installing on FrappeCloud
-Site is currently on Frappe Version 14.76.1
-Site is currently configured for Node Version 14.19.0

Deployment error shows: 

insights depends on version insights-frontend of 14.19.0. Found version is >=16.0.0
To fix this issue please set 14.19.0 to version insights-frontend.

**Comment by nextchamp-saqib** [comment]
This has been fixed. Please check
