### ISSUE TITLE
feat: Support for creating pivot tables.

### ISSUE THREAD

**Issue by mujeerhashmi** [frappe/insights#26]
The support for pivot tables will make this awesome app a great BI tool.

**Comment by nextchamp-saqib** [comment]
Implemented a basic version of it.

![CleanShot 2022-11-20 at 18 49 13](https://user-images.githubusercontent.com/25369014/202904306-e4ac5416-d679-4171-af17-73a01f41aeb2.gif)

Will add more options like - sorting & summation later
