### ISSUE TITLE
Unable to install-app insights.

### ISSUE THREAD

**Issue by alixo91** [frappe/insights#264]
Unable to install insights. Getting error as below 

<details><summary>Details of Error</summary>
<p>

Installing insights...
An error occurred while installing insights: ('Module Def', 'Insights', IntegrityError(1062, "Duplicate entry 'Insights' for key 'PRIMARY'"))
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 445, in install_app
    _install_app(app, verbose=context.verbose, force=force)
      context = {'sites': ['erp.zaidtec.com'], 'force': False, 'verbose': False, 'profile': False}
      apps = ('insights',)
      force = False
      _install_app = <function install_app at 0x7878f71368e0>
      filelock = <function filelock at 0x7878f7134220>
      exit_code = 0
      site = 'erp.zaidtec.com'
      app = 'insights'
      err = DuplicateEntryError('Module Def', 'Insights', IntegrityError(1062, "Duplicate entry 'Insights' for key 'PRIMARY'"))
  File "apps/frappe/frappe/installer.py", line 299, in install_app
    add_module_defs(name, ignore_if_duplicate=force)
      name = 'insights'
      verbose = False
      set_as_patched = True
      force = False
      sync_jobs = <function sync_jobs at 0x7878f59725c0>
      sync_for = <function sync_for at 0x7878f5973380>
      sync_customizations = <function sync_customizations at 0x7878f7108c20>
      sync_fixtures = <function sync_fixtures at 0x7878f59736a0>
      app_hooks = {'app_color': ['grey'], 'app_description': ['Powerful Reporting Tool for Frappe Apps'], 'app_email': ['hello@frappe.io'], 'app_icon': ['octicon octicon-file-directory'], 'app_license': ['GNU GPLv3'], 'app_name': ['insights'], 'app_publisher': ['Frappe Technologies Pvt. Ltd.'], 'app_title': ['Frappe Insights'], 'app_version': ['1.1.3'], 'before_tests': ['insights.tests.utils.before_tests'], 'fixtures': [{'dt': 'Insights Data Source', 'filters': {'name': ('in', ['Site DB', 'Query Store'])}}], 'has_permission': {'Insights Data Source': ['insights.overrides.has_permission'], 'Insights Table': ['insights.overrides.has_permission'], 'Insights Query': ['insights.overrides.has_permission'], 'Insights Dashboard': ['insights.overrides.has_permission']}, 'scheduler_events': {'all': ['insights.insights.doctype.insights_alert.insights_alert.send_alerts']}, 'setup_wizard_requires': ['assets/insights/js/setup_wizard.js'], 'setup_wizard_stages': ['insights.setup.setup_wizard.get_setup_stages'], 'websi...
      installed_apps = ['frappe', 'erpnext']
  File "apps/frappe/frappe/installer.py", line 639, in add_module_defs
    d.insert(ignore_permissions=True, ignore_if_duplicate=ignore_if_duplicate)
      app = 'insights'
      ignore_if_duplicate = False
      modules = ['Insights']
      module = 'Insights'
      d = <ModuleDef: Insights>
  File "apps/frappe/frappe/model/document.py", line 302, in insert
    self.db_insert(ignore_if_duplicate=ignore_if_duplicate)
      self = <ModuleDef: Insights>
      ignore_permissions = True
      ignore_links = None
      ignore_if_duplicate = False
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "apps/frappe/frappe/model/base_document.py", line 577, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
      self = <ModuleDef: Insights>
      ignore_if_duplicate = False
      conflict_handler = ''
      d = {'name': 'Insights', 'creation': '2024-06-21 01:00:29.843307', 'modified': '2024-06-21 01:00:29.843307', 'modified_by': 'Administrator', 'owner': 'Administrator', 'docstatus': 0, 'idx': 0, 'module_name': 'Insights', 'custom': 0, 'package': None, 'app_name': 'insights', 'restrict_to_domain': None, '_user_tags': None, '_comments': None, '_assign': None, '_liked_by': None}
      columns = ['name', 'creation', 'modified', 'modified_by', 'owner', 'docstatus', 'idx', 'module_name', 'custom', 'package', 'app_name', 'restrict_to_domain', '_user_tags', '_comments', '_assign', '_liked_by']
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Insights', IntegrityError(1062, "Duplicate entry 'Insights' for key 'PRIMARY'"))

</p>
</details>

**Comment by sunil-mel** [comment]
Delete the entry of `Insights` manually from "Module Def" table and try again.

**Comment by nextchamp-saqib** [comment]
Please try the suggested fix, if it doesn't work, add a comment here to reopen
