### ISSUE TITLE
Better Documentation on installing steps for Insights Local

### ISSUE THREAD

**Issue by ArchishmanSengupta** [frappe/insights#277]
The current local installation steps are not extensive. Add steps from cloning repo and then using `frappe-bench`

**Comment by nextchamp-saqib** [comment]
Local steps does mention all the steps needed to install Insights
`bench get-app insights` clones the repo so no need to do it

![CleanShot 2024-09-09 at 14 15 04](https://github.com/user-attachments/assets/dc0bfc8a-8e81-47db-9faa-7035aa478f8c)
