### ISSUE TITLE
SQLite data source, and Missing Icons

### ISSUE THREAD

**Issue by fenilgmehta** [frappe/insights#278]
Hi team,
I started fresh instance of Insights and loaded demo data for exploring. Following is how `/insights/data-source` looks:
![image](https://github.com/user-attachments/assets/6e94768d-84b3-4782-a5bc-510ba4fc8025)

Now, I want to add an SQLite db file from my device as a data source.
![image](https://github.com/user-attachments/assets/19a2f95f-b124-4794-ad8e-574031a74910)

I found two issues:
1. The icons are not loading. Following are the network logs
    ![image](https://github.com/user-attachments/assets/4f82f501-02ea-4167-af46-5766ae3ff494)
2. Sample data has SQLite as a data source. But, we don't get option to add it from GUI.

Thanks🙏

**Comment by nextchamp-saqib** [comment]
Do you want to create a new SQLite database? or import an existing SQLite database?

**Comment by samy4sam** [comment]
The icons don't load for me either.

**Comment by nextchamp-saqib** [comment]
The icons are fixed in the latest version

**Comment by fenilgmehta** [comment]
> The icons are not loading. Following are the network logs
Thanks for fixing issue 1

> Sample data has SQLite as a data source. But, we don't get option to add it from GUI.
>> Do you want to create a new SQLite database? or import an existing SQLite database?
I do NOT want to create a new SQLite database from Insights. Rather, I would like to use SQLite as a source of data which I would like to Visualize using Insights.
