### ISSUE TITLE
insights is not appearing in ERPNext 15 awesome search bar

### ISSUE THREAD

**Issue by kitunzit** [frappe/insights#282]
Hi guys,
I have successfully installed insights on cloud cluster ERPNext 15 with no any error but it's not appearing in the awesome search bar.
Has anyone encountered  this problem.

**Comment by nextchamp-saqib** [comment]
Can you check if you can access frappe insights by manually visiting `/insights` route?

**Comment by kitunzit** [comment]
![insight issue image](https://github.com/user-attachments/assets/72035e6b-9e72-46d4-afac-614897d07692)
I have uninstalled & reinstalled insights but am still facing the same issue

**Comment by femijoshuao** [comment]
I encounter the same issue. After succcessful installation Insights did not open via /insights route.

**Comment by pu-raihan** [comment]
Check if the app installed correctly by Help > About > Installed Apps in the desk view.
If it's installed then the problem might be related with the build. 
If so try `cd apps/insights/frontend` 
then run `yarn build`
this might fix the problem
