### ISSUE TITLE
Add new dashboard not working

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/insights#29]
<img width="572" alt="CleanShot 2022-10-11 at 19 53 44@2x" src="https://user-images.githubusercontent.com/25369014/195117953-4b4d9340-8544-4a30-bce8-fb6481d69c48.png">

**Comment by chandrubiradar** [comment]
Still the issue exists
Please refer to my screenshots.

![Screenshot (652)](https://user-images.githubusercontent.com/47516435/199472179-45c98e85-3a1e-4413-9cdd-0455807b1d10.png)
![Screenshot (653)](https://user-images.githubusercontent.com/47516435/199472185-eba637cd-4e15-4895-a185-c3508e752488.png)

**Comment by nextchamp-saqib** [comment]
Fixed with 2b58d09922b90ebaadd2405e5711a5c4f6e0ec70
