### ISSUE TITLE
Join Single Table with multiple columns using Custom Join Condition 

### ISSUE THREAD

**Issue by sunil-mel** [frappe/insights#297]
I tried latest insights with below branches and connected to PostgresDB. I was able to select tables and join other tables from the given options however I have 2 queries regarding the same

```
Frappe Framework: v15.37.0 (version-15)
Frappe Insights: v3.0.0 (develop)
```

1. Is there an option to enter full SQL query without selecting tables and its join ?
2. How can I join a table with multiple columns (I can only add single column join) ? In this context how can I use Custom Join Condition to join the table with multiple columns.
eg: LEFT JOIN table_name as tab2 ON tab2.col1 = tab1.col2 
       AND tab2.col3 = tab3.col4

![image](https://github.com/user-attachments/assets/cceed3a2-55d2-4dc5-8616-a1b8bb2b40cf)

Help would be very much appreciated.

**Comment by nextchamp-saqib** [comment]
The help text and descriptions are missing currently, but this info will be added soon for users to figure out

You can use `t1` and `t2` to reference the tables being joined. For example you can do `t1.column = t2.column and t1.column > 0`

Also, there will be a "custom code" step soon, using it you can perform any SQL operation by writing python code
