### ISSUE TITLE
Split Y Axis toggle disappears incorrectly.

### ISSUE THREAD

**Issue by kurogeek** [frappe/insights#298]
https://github.com/frappe/insights/blob/7dfd555d480d335b5fbde905c3cb03773c1a7cb2/frontend/src/widgets/AxisChart/AxisChartOptions.vue#L143

This condition should be` >= 2`.

**Comment by nextchamp-saqib** [comment]
if split y axis is enabled for more than two series then the right axis is 
![CleanShot 2024-09-09 at 13 54 23](https://github.com/user-attachments/assets/9b30ea32-7b7c-47d0-9d51-126c5741694a)



![CleanShot 2024-09-09 at 13 54 32](https://github.com/user-attachments/assets/cc68fcb4-962f-4368-ad0f-e01864ac8802)
