### ISSUE TITLE
[Bug] Filter cannot be set if filtered value is 0. 

### ISSUE THREAD

**Issue by samy4sam** [frappe/insights#302]
Filter cannot be set if filtered value is 0. 
![image](https://github.com/user-attachments/assets/8261113b-4376-4f0d-8e41-77bbd076ac85)

As soon as the value is greater, the filter can be applied.
![image](https://github.com/user-attachments/assets/550307c1-90b4-43e8-8a88-fb7a0a763a9f)

Insights Version: v3.0.1-beta

**Comment by nextchamp-saqib** [comment]
fixed by #306
