### ISSUE TITLE
[Bug] Stack option is set by default but bars are not stacked

### ISSUE THREAD

**Issue by samy4sam** [frappe/insights#304]
The “Stack” option in the bar chart is activated by default, but the bars are not stacked.
The bars are stacked after switching the option off and on.
![image](https://github.com/user-attachments/assets/16ffb81a-d242-4632-8e4c-979ab4137845)

Insights Version: v3.0.1-beta

**Comment by nextchamp-saqib** [comment]
fixed by #305
