### ISSUE TITLE
Unable to install a "full version", seemingly

### ISSUE THREAD

**Issue by AthletiCoder** [frappe/insights#310]
I have been working on a ERPNext instance for a while now. Because of the relatively simple native charting features I decided to try out Insights alongside the local erpnext application. I followed [these installation steps](https://github.com/frappe/insights?tab=readme-ov-file#local) and I ended up getting a "limited version" of insights (sidebar has no query builder and other options)

<img width="1431" alt="Screenshot 2024-09-06 at 10 05 48 PM" src="https://github.com/user-attachments/assets/2d1be953-7b79-4b73-a94e-edbb18900b29">

I tried clearing the cache and reinstalling multiple times but nothing seems to work

**Comment by nextchamp-saqib** [comment]
This is the newer version 3 beta of Insights, the "full version" you are referring to is version 2 (stable)
Switch to `main` branch to use the version 2 of Insights
