### ISSUE TITLE
Update Doctype Name does not reflect in Insights

### ISSUE THREAD

**Issue by ablashek** [frappe/insights#318]
Hi,

I had a table name called "ABC" and generated few queries using this. Later I updated the table naem to "BCD" due to some internal reason. When I went back into Insights the old table name, ABC, was still being referenced. So no issues, I will change manually ... but the probelm now is that the new table name, "BCD" does not how up in the drop down. And the first table name still shows up. If I try to save it as is, it generates a toast message saying that table name does not exist.

**Comment by nextchamp-saqib** [comment]
You have to go to the data source and from the 3-dot menu sync tables to update the new table list

![CleanShot 2024-09-12 at 11 55 59@2x](https://github.com/user-attachments/assets/a88d7fe7-7d2f-4a6d-bcab-1c1d2216d3c2)
