### ISSUE TITLE
Unable to modify limit in Table Chart

### ISSUE THREAD

**Issue by zaheer-srushty** [frappe/insights#332]
By default, the Table Chart displays 100 rows. It is not showing the entire row result. If the limit is increased, then anl SQL error is raised.

![Screenshot_20241022-135008](https://github.com/user-attachments/assets/1f63e64d-64da-4f2e-b729-160425ddc895)

This gives a SELECT error whereas I was thinking the SQL syntax should be applying the LIMIT keyword.

**Comment by nextchamp-saqib** [comment]
I can't replicate the issue. The limit is applied correctly. Can you share the chart options that you have set?

**Comment by zaheer-srushty** [comment]
Here's the chart options

![image](https://github.com/user-attachments/assets/0cc51620-6d62-47da-b7ee-ee375f6c4311)

**Comment by nextchamp-saqib** [comment]
It works for me with the same options, can you try creating a new table chart with the same options and check if you can replicate it again?

**Comment by nextchamp-saqib** [comment]
Should be fixed with 6ddbb9580b447376c27af464e5b38aa6e99d9bfd (v3.0.7)
