### ISSUE TITLE
Filter widget in dashboard not displaying columns from queries using WEEK, DATE_SUB, and DAYOFMONTH

### ISSUE THREAD

**Issue by Nitin1692** [frappe/insights#336]
I am encountering an issue where the filter widget in the dashboard does not show any columns from SQL queries that use the functions WEEK, DATE_SUB, or DAYOFMONTH. This issue hinders my ability to filter the data effectively based on these columns.

**Comment by nextchamp-saqib** [comment]
Dashboard filters are not supported for SQL queries in the current version, but there is a workaround for it (https://t.me/frappeinsights/2190/2192)

This feature will be available in the next release (version 3)
