### ISSUE TITLE
Data based on User Permissions of Frappe

### ISSUE THREAD

**Issue by vineyrawat** [frappe/insights#362]
Can we get data based on the current user's permission?

for example:
if Employee A has access to only the Records of Employee B and C then it should show only the data of these three employees
(can we achieve this using custom operations)?

**Comment by nextchamp-saqib** [comment]
I have added a toggle to enable user permission check in the settings

![CleanShot 2024-12-03 at 16 59 41@2x](https://github.com/user-attachments/assets/edd10de6-ad1b-4e3d-a734-f3063f6aa378)

Update to v3.0.9 and check if it works as expected
