### ISSUE TITLE
Bring back the older pivot 'dual-row' columns

### ISSUE THREAD

**Issue by NehaSan16** [frappe/insights#366]
Current
<img width="893" alt="Screenshot 2024-11-24 at 6 28 58 PM" src="https://github.com/user-attachments/assets/be05fbf8-90ae-4a61-9a61-6128a6c6941b">

Old
<img width="1270" alt="Screenshot 2024-11-24 at 6 29 10 PM" src="https://github.com/user-attachments/assets/88a2f8e3-0ed4-4a68-9bf2-8b97a1e9d239">

Also, older filtering UX was much better.

**Comment by nextchamp-saqib** [comment]
fixed: 6b5d71113af53df6bb43eb0d27f08f6c30c4865e
