### ISSUE TITLE
Can't connect to PostgreSQL data source.

### ISSUE THREAD

**Issue by kittiu** [frappe/insights#374]
Frappe Insights: v3.0.8 (HEAD)

I was successfully connect with VS Code, but not with Inisght v3

![image](https://github.com/user-attachments/assets/9186d994-cfae-4aa9-a854-57fadc86ba00)

Nothing happen after click refreshed

![image](https://github.com/user-attachments/assets/1619f215-9e4d-4465-a6f8-9e64e15bbb97)

![image](https://github.com/user-attachments/assets/1ac08381-fe96-424b-8ef2-6f13acfa8489)

**Comment by nextchamp-saqib** [comment]
Can you check if there's any error in the browser console or error log doctype?

**Comment by kittiu** [comment]
Nop, no error. Also the amount of time it take when refresh feel like it is connecting to DB, not just turn down and error.

![Screenshot from 2024-12-05 09-59-35](https://github.com/user-attachments/assets/d3b36dbe-2941-4780-bff9-b2bf810b33f8)

Are there any setting in target database that you suspect? Note that, VS Code is connecting just fine.

**Comment by nextchamp-saqib** [comment]
This should fix the issue: https://github.com/frappe/insights/commit/292e922e0db1d671c9eb6a9684fc54cf97ac359e
Update to v3.0.11 and check

**Comment by kittiu** [comment]
Thank you, it works now.
