### ISSUE TITLE
Column name should not be empty

### ISSUE THREAD

**Issue by jeshani** [frappe/insights#380]
Try to rename column name,
Erase all character,
Press enter. 

if no new name given it should retain previously given name. Or alert.

![null column name](https://github.com/user-attachments/assets/0926df4f-ea1e-46a0-8df4-cc46ff820dcf)

**Comment by nextchamp-saqib** [comment]
fixed: 1fe190895fc0c32f0ba6aabd48e7e7ec0bd13813
