### ISSUE TITLE
Aggregate count and distinct count are missing.

### ISSUE THREAD

**Issue by jeshani** [frappe/insights#382]
before it was allowing to aggregate count and distinct count on String column, after updating to 3.0.9 it disappear. 

![image](https://github.com/user-attachments/assets/ba6cb09d-e4a4-402f-b49c-ea0070d49c27)

**Comment by nextchamp-saqib** [comment]
It is possible to change the aggregate function once you select the column. For eg. if you want to "average of grand total" then select "sum_of_grand_total" first and then click on the gear icon next to it to find the option to change the aggregate function

![CleanShot 2024-12-06 at 17 02 41@2x](https://github.com/user-attachments/assets/bb477c8d-dbfa-4f8f-969d-9ed1a857b74a)


This is not a good ux, I am working on improving this by making it a two step process.

**Comment by jeshani** [comment]
Thank to point out that we have options to select functions, But still am unable to select the desired column. 
I have column name 'Customer' as string. 
How to distinct count customer? 

![aggregate](https://github.com/user-attachments/assets/64d07a69-559e-4bf8-ada7-ff9e3d8eef60)

**Comment by nextchamp-saqib** [comment]
fixed in 3.0.11
