### ISSUE TITLE
Unable to add chart on dashboard

### ISSUE THREAD

**Issue by jeshani** [frappe/insights#383]
v3.0.10

There are no focusable elements inside the <FocusTrap />

![add_chart](https://github.com/user-attachments/assets/7c60ac05-46c4-4018-9f47-acfd0fa76190)

**Comment by jeshani** [comment]
This only occurs when first chart is deleted, and space remain empty in the begging.

**Comment by nextchamp-saqib** [comment]
By deleted you mean it is removed from the workbook itself or just from the dashboard?

**Comment by jeshani** [comment]
> By deleted you mean it is removed from the workbook itself or just from the dashboard?

deleted from workbook

**Comment by nextchamp-saqib** [comment]
fixed: 025376d5f4bcde0d5e86f19091e3c5ea1c903b17
