### ISSUE TITLE
Table pagination if limit >100

### ISSUE THREAD

**Issue by jeshani** [frappe/insights#385]
v3.0.9

Even though limit is increased from default 100, table data only shows max 100 rows.

Query execution log:
![image](https://github.com/user-attachments/assets/81bcec4c-7814-4536-9edd-0d4118e790ec)

Table data:
![image](https://github.com/user-attachments/assets/b443f024-6db6-4f0e-939b-d52d51ce712a)

**Comment by nextchamp-saqib** [comment]
fixed in 3.0.12
