### ISSUE TITLE
error in joining tabSingles if User Permission is enabled!

### ISSUE THREAD

**Issue by vineyrawat** [frappe/insights#395]
I'm writing a query that includes a join of `tab singles`.
It works fine if user permission is disabled but it throws an error as soon as we enable user permissions.

**Comment by vineyrawat** [comment]
<img width="900" alt="Screenshot 2024-12-13 at 12 56 28 PM" src="https://github.com/user-attachments/assets/f85727e4-ff53-4b6a-9c20-6d6a08a621f2" />

For now I managed to bypass this by not applying and permission

**Comment by nextchamp-saqib** [comment]
should be fixed now with this 0d34cd294db556a5af61c7489d48ef695898cecf
