### ISSUE TITLE
Cumulative sum for calculating running totals

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/insights#40]

**Comment by nextchamp-saqib** [comment]
Done!

<img width="1440" alt="CleanShot 2022-11-20 at 20 55 24@2x" src="https://user-images.githubusercontent.com/25369014/202910651-f6673d55-e0c3-4ba9-b37a-7cd8807457e7.png">


<img width="1440" alt="CleanShot 2022-11-20 at 20 56 16@2x" src="https://user-images.githubusercontent.com/25369014/202910674-2462e73f-9836-44ef-b5cf-398373e03cb0.png">

**Comment by azurre931** [comment]
Is there a way of using Cumulative Sum in custom expression?

**Comment by frankymcgee** [comment]
@azurre931, not quite sure if you are still wondering about this but you can utilise the transform option to change it to a cumulative sum:

sum(case(`COLUMN` = VALUE,1,0))
