### ISSUE TITLE
Error in Explore a dummy database

### ISSUE THREAD

**Issue by Shankarv19bcr** [frappe/insights#46]
![issue](https://user-images.githubusercontent.com/95605398/197701561-25396bee-866e-4cab-930e-941ebbd992ca.png)

**Comment by NagariaHussain** [comment]
I think the issue is that the function `is_job_queued` only exists in `develop` and not version 14: https://github.com/frappe/frappe/pull/18091 .

**Comment by nextchamp-saqib** [comment]
I'll get this fixed. For now, you can go to Insights Settings and check "setup complete" and then open Insights

**Comment by nextchamp-saqib** [comment]
Fixed with 1cdb279e2a5888ea4bdf5e2250033de74865c958
