### ISSUE TITLE
Unable to add charts to Dashboard

### ISSUE THREAD

**Issue by chandrubiradar** [frappe/insights#49]
I have created Dashboard. I have created 3 queries. I am able to add 1st query to the Dashboard. For other 2 queries I will not get Dashboard name. 
Even if I add directly I get loading screen.
![Screenshot (653)](https://user-images.githubusercontent.com/47516435/199471474-ad2a7f1f-0f16-4d40-b975-7cd21c3c8500.png)
![Screenshot (652)](https://user-images.githubusercontent.com/47516435/199471479-6a5f3783-1812-40e7-942b-c58089db983d.png)

**Comment by nextchamp-saqib** [comment]
@chandrubiradar  I have pushed a fix. Can you update and check?

**Comment by chandrubiradar** [comment]
Thanks for the quick fix
I will check and update you

**Comment by chandrubiradar** [comment]
Thanks @nextchamp-saqib for your quick and great work.
I really appreciate it
