### ISSUE TITLE
Query Doc error

### ISSUE THREAD

**Issue by AlaaBadry** [frappe/insights#5]
![image](https://user-images.githubusercontent.com/26534497/183132459-6e39c261-a2b4-4c8f-966f-991cb7c0e54d.png)

Database name is selected

**Comment by nextchamp-saqib** [comment]
This happens only with `version-13` branch of `frappe/frappe`

There are 2 fixes for now,
either switch to `version-14` branch of `frappe/frappe`
or, modify the `fieldtype` of `database_type` field to `Select` in `data_source.json` file and then migrate

**Comment by NavinThirvusoft** [comment]
> This happens only with `version-13` branch of `frappe/frappe`
> 
> There are 2 fixes for now, either switch to `version-14` branch of `frappe/frappe` or, modify the `fieldtype` of `database_type` field to `Select` in `data_source.json` file and then migrate

Having the same error  even after with `version-14` branch of `frappe/frappe`  and also I've tried modifying the `fieldtype` of `database_type` field to `Select`
![Screenshot from 2022-08-13 18-50-31](https://user-images.githubusercontent.com/95605431/184497192-887303f4-6689-486d-9221-20a9c6e92523.png)
![Screenshot from 2022-08-13 19-20-36](https://user-images.githubusercontent.com/95605431/184497212-be2057b3-48e7-44fd-a352-4b8d845025b0.png)

**Comment by nextchamp-saqib** [comment]
Okay, my bad, the error is due to username being `root`

You can only use Database Name from `site_config` as Username, i.e your Database Name and Username should be same, which you can find in `site_config.json`

**Comment by nextchamp-saqib** [comment]
Check #7 for a fix

**Comment by Grolaf** [comment]
Hello, what whoud you type as Password ?
I actually tried to type Database Name and Username like "database_name" on `site_config.json` like you said, but the password is apparently not valid (I got "Failed, Retry ?" message).

I also tried with the root password, but it does not work more...

**Comment by nextchamp-saqib** [comment]
Password 

> Hello, what whoud you type as Password ? I actually tried to type Database Name and Username like "database_name" on `site_config.json` like you said, but the password is apparently not valid (I got "Failed, Retry ?" message).
> 
> I also tried with the root password, but it does not work more...

Password comes from `db_pass` field in site_config.json
Does that not work?

Your Host and Port fields should be empty

**Comment by Grolaf** [comment]
Hey @nextchamp-saqib and thanks for your answer ! 

After many tries, I saw that I couldn't copy the db_password from `site_config.json`. I fixed that and now it works, so your solution is great. Thank you very much !
