### ISSUE TITLE
Sharable "Insight packages" - "Orbs"

### ISSUE THREAD

**Issue by ankush** [frappe/insights#65]
Basically let user/developer package bunch of dashboards, charts, reports, queries into a neat package that others can import. 

Many use-cases:

- ERPNExt devs can share packages that provide report and dashboard for POS module
- Custom dashboards that only some countries need
- Custom dashboards prepared by devs, deployed on multiple sites (think ERP implementers)
- Power users with big-brains can write and share their powerful custom reporting. Think of how people share excel spreadsheets online for sharing a cool analysis technique.

**Comment by aakvatech** [comment]
This will help to create KPI packages for each business area or module.

**Comment by ankush** [comment]
Cool name for packages "Insight Orb" :crystal_ball:  :woozy_face:

**Comment by NagariaHussain** [comment]
I was just thinking about this yesterday, new products like FrappeCRM can have their own “Orbs” which can be accessed when Frappe Insights is installed along with it. That would be very useful.

**Comment by ankush** [comment]
This is possible with templates now
