### ISSUE TITLE
Enhance Dashboard Filters

### ISSUE THREAD

**Issue by michellealva** [frappe/insights#70]
- [x] Refresh the dashboard only on save and not on every application of the filter
- [x] #80
- [x] Highlight the filter button in charts where the filter is applied

**Comment by nextchamp-saqib** [comment]
https://user-images.githubusercontent.com/25369014/212667683-242051af-ad11-4720-809c-c01bdb63cba5.mp4

commit. d3aa5581af7fa3bbe8f61d091930542e6ff5d96c
