### ISSUE TITLE
Feature Request-Charts | Filters

### ISSUE THREAD

**Issue by arunrmit** [frappe/insights#73]
- [ ] Currently, there is no options to add data labels over the charts
![image](https://user-images.githubusercontent.com/26267551/206840348-9e732fe2-c177-4629-945d-cb55e5fb7b0b.png)

- [ ] Nice to have an option to format reference line numbers in the charts
![image](https://user-images.githubusercontent.com/26267551/206840334-984b0993-493e-4d17-9d18-b27082802f9f.png)

- [x] Filters in the dashboard should have the drop-down list based on the unique value from the column assigned
![image](https://user-images.githubusercontent.com/26267551/206840612-57d18a8a-aabc-4b4b-912c-809395d8d48e.png)

- [x] Nice to have an option to update Y-axis label
![image](https://user-images.githubusercontent.com/26267551/206840618-07b41998-03fd-45f6-858d-a0ec3f4eea11.png)

**Comment by nextchamp-saqib** [comment]
> Nice to have an option to update Y-axis label

The column labels are linked with the axis labels, so for now you can change the label of the column to change the Y-axis column

**Comment by nextchamp-saqib** [comment]
> Filters in the dashboard should have the drop-down list based on the unique value from the column assigned

https://github.com/frappe/insights/issues/70#issuecomment-1383905715
