### ISSUE TITLE
Select Number format

### ISSUE THREAD

**Issue by Suprazz** [frappe/insights#75]
I would like to be able to choose how to display big numbers
Right now it seems to be fixed to format like this:
99 000 is displayed 99k
100 000 is displayed 1.0L (this is really unintuitive for me). 100k would be better up to 1M).
I would like to be able to choose how to display big numbers. Use this formatting, or display full number (100 000.00).

**Comment by azurre931** [comment]
Same here, 1.0L is not intuitive!

**Comment by nextchamp-saqib** [comment]
It is now configurable. You can set the **Language** in the **System Settings** which will be used to format the numbers in Insights
