### ISSUE TITLE
erpnext insights issue #404 not not found error

### ISSUE THREAD

**Issue by csdindia07** [frappe/insights#8]
I follow instructions of frappe insights to install insights in ubuntu 20.04 but  page is not found error is coming
![Screenshot from 2022-08-22 08-46-13](https://user-images.githubusercontent.com/97270430/185831679-1dd9e42d-8110-4fd6-9e7b-6ddc4b60099a.png)
.

**Comment by nextchamp-saqib** [comment]
Can you check if your `bench build` command completes successfully?

I too have faced this error, and it happens only when `bench build` has failed

**Comment by csdindia07** [comment]
after i run bench build i got this and error is not solved yet.
![Screenshot from 2022-08-23 13-39-15](https://user-images.githubusercontent.com/97270430/186106548-f9b98def-0d90-401c-8504-75bbb7b9d4b7.png)

**Comment by csdindia07** [comment]
Thanks @nextchamp-saqib your suggestion...i got the error solved and its working fine.
