### ISSUE TITLE
Adding "Descendants of" in filters

### ISSUE THREAD

**Issue by azurre931** [frappe/insights#85]
In ERPNext there is the filter : "Descendants of", but there is no way to put it in Insights.

**Comment by michellealva** [comment]
You can add it in the expression of the filter

![image](https://user-images.githubusercontent.com/50285544/213343349-d6fa1f38-2a43-44c0-bfc9-ff4e3cdf2c27.png)

**Comment by azurre931** [comment]
> @azurre931 You can add it in the expression of the filter
> 
> ![image](https://user-images.githubusercontent.com/50285544/213343349-d6fa1f38-2a43-44c0-bfc9-ff4e3cdf2c27.png)

Thank you for you answer!

what would be the expression equivalent of : `tabSales Invoice.customer_group` "descendants of" "B2C"

When writting d, there is nothing appearing : 

![image](https://user-images.githubusercontent.com/65413319/213453345-8052b8f7-7151-46cf-bf3b-a8f66ba3a54d.png)


Thank you!

**Comment by nextchamp-saqib** [comment]
Are you on the latest commit?

**Comment by azurre931** [comment]
> Are you on the latest commit?

Probably not : 

![image](https://user-images.githubusercontent.com/65413319/213546894-00b57fbf-5e9c-40ea-8ad9-44b9d417c86c.png)

**Comment by nextchamp-saqib** [comment]
Can you update your app and check if it works?

**Comment by azurre931** [comment]
Works with update

**Comment by azurre931** [comment]
Hi @nextchamp-saqib 

Can you tell me why descendants not working here : 

descendants_and_self("B2C", "tabSales Invoice", `tabSales Invoice.customer_group`)

![image](https://user-images.githubusercontent.com/65413319/220374282-5b7553b7-e891-434a-b13e-17ec44047127.png)


Thank you for your help
