### ISSUE TITLE
Password with character '@'

### ISSUE THREAD

**Issue by nrhdasa** [frappe/insights#92]
If I have a password containing `@`, the pymysql driver is not able to read it properly.

Please look into it.

https://github.com/frappe/insights/blob/f860ae7941f210ef09aa215f485867429b2c44af/insights/insights/doctype/insights_data_source/sources/mariadb.py#L110-L128

**Comment by nextchamp-saqib** [comment]
Fixed with 5509e511986d7fbfbd805b66cd2dc7fdff64dc45
