### ISSUE TITLE
Problem with grouping by days of the week duplicate

### ISSUE THREAD

**Issue by azurre931** [frappe/insights#93]
Hi, 

There is a problem with grouping by days of the week where "Wednesday" is missing and there is duplicate of "Thursday" 

![image](https://user-images.githubusercontent.com/65413319/216503566-3fd4e089-a6f4-402f-8712-f9dc9c6d8d11.png)

**Comment by nextchamp-saqib** [comment]
I was able to replicate, I'll fix it soon

**Comment by nextchamp-saqib** [comment]
fixed with 5c743f1241276c9a61d38da633862018e190f5ce
