### ISSUE TITLE
Add button not disabled when Chart selector is empty

### ISSUE THREAD

**Issue by 18alantom** [frappe/insights#95]
![Screen Shot 2023-02-16 at 12 30 56](https://user-images.githubusercontent.com/29507195/219291795-0be39882-8227-4efe-a857-e1f76a780699.png)

Clicking on Add (which is not disabled) creates a chart that causes this:

![Screen Shot 2023-02-16 at 12 34 14](https://user-images.githubusercontent.com/29507195/219292313-93584e0e-883a-4438-9b85-529f5fb3d64c.png)

(Note: I didn't mean stress test it, it's the kinda thing that happens on clicking around willy-nilly without knowing what does what)

**Comment by nextchamp-saqib** [comment]
fixed with a new dashboard layout
